language: objective-c
osx_image: xcode61
rvm:
- 2.1.2
cache:
  directories:
    - ./Unity
before_install:
- chmod a+x ./Scripts/install.sh
install:
- ./Scripts/install.sh
before_script:
- chmod a+x ./Scripts/build.sh
script:
- ./Scripts/build.sh
sudo: required